ViewModels/ChangePassword.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UserRegistrationAssignment_V1.ViewModels
{
    public class ChangePassword
    {
        public class UserLogin
        {
            [Required]
            [Display(Name = "Email")]
            [EmailAddress]
            public string EmailId { get; set; }

            [Required]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [Required(ErrorMessage = "You must provide a password")]
            [DataType(DataType.Password)]
            [Display(Name = "New Password")]
            public string NewPassword { get; set; }

            [Required(ErrorMessage = "You must provide the same password")]
            [DataType(DataType.Password)]
            [Compare("NewPassword", ErrorMessage = "The password and confirmation password do not match.")]
            [Display(Name = "Confirm New Password")]
            public string ConfirmPassword { get; set; }
        }
    }
}

ViewModels/UserLogin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UserRegistrationAssignment_V1.ViewModels
{
    public class UserLogin
    {
        [Required]
        [Display(Name = "Email *")]
        [EmailAddress]
        public string EmailId { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password *")]
        public string Password { get; set; }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UserRegistrationAssignment_V1.ViewModels;
using UserRegistrationAssignment_V1.UserModelContext;
using System.Web.Security;

namespace UserRegistrationAssignment_V1.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult UserLogin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UserLogin(UserLogin userLogin)
        {
            if (!ModelState.IsValid)
            {
                return View(userLogin);
            }
            using (UserAccountContext obj=new UserAccountContext())
            {
                string pass = PasswordClass.Encrypt(userLogin.Password);
                var userData = obj.UserDetails.FirstOrDefault(x => x.Email == userLogin.EmailId && x.Password == pass);
                if (userData != null)
                {
                    Session["email"] = userLogin.EmailId;
                    Session["password"] = pass;
                    ViewBag.messageLogin = "Login successful";
                    return RedirectToAction("UserDetails", "Home");
                }
                else
                {
                    ViewBag.messageLogin = "Invalid email or password";
                }
            }
            return View();
        }
        public ActionResult UserLogout()
        {
            
            Session["email"] = null;
            Session["password"] = null;
            return RedirectToAction("UserLogin");
        }
        public ActionResult ChangePassword()
        {
            return View();
        }

    }
}

Views/Login/ForgotPassword.cshtml
@model UserRegistrationAssignment_V1.ViewModels.PasswordReset
@using UserRegistrationAssignment_V1.ViewModels
@{
    ViewBag.Title = "ForgotPassword";
}

<h2>Forgot Password</h2>
@using (Html.BeginForm("ForgotPassword", "Login", FormMethod.Post, new { @class = "registration", role = "form" }))
{
        @Html.LabelFor(m => m.EmailId)
        @Html.TextBoxFor(m => m.EmailId, new { placeholder = "Enter Your Email" })
        <span class="invalid-input">@Html.ValidationMessageFor(m => m.EmailId)</span>
        <span class="invalid-input">@ViewBag.invalidEmailmMessage</span>

        <div>
            <button type="submit" value="Submit" id="SendCodeButton">Get Reset Link</button>
        </div>
}

Views/Login/UserLogin.cshtml
@model UserRegistrationAssignment_V1.ViewModels.UserLogin
@{
    ViewBag.Title = "Login";
}


@using (Html.BeginForm("UserLogin", "Login", FormMethod.Post, new { @class = "registration", role = "form" }))
{
    <div class="tab-group">
        <span class="btn btn-outline-primary tag-signup"><a href="/Registration/Register">Sign Up</a></span>
        <span class="btn btn-outline-primary tag-login"><a href="/Login/UserLogin">Log In</a></span>
    </div>
    @Html.AntiForgeryToken()
    <h3 class="form-heading">Login</h3>
    <div class="note-message">
        <span class="text-danger">Note:Fields marked with * are mandatory.</span>
    </div>

    <div class="row">
        <div class="form-group">
            <div class="col-md-4">
                @Html.LabelFor(m => m.EmailId, new { @class = "control-label" })
            </div>
            <div class="col-md-8">
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                    @Html.TextBoxFor(m => m.EmailId, new { @class = "form-control", placeholder = "Enter Your Email" })
                </div>
            </div>
        </div>
    </div>

        <div class="row">
            <div class="form-group">
                <div class="col-md-4">
                    @Html.LabelFor(m => m.Password, new { @class = "control-label" })
                </div>
                <div class="col-md-8">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        @Html.TextBoxFor(m => m.Password, new { @class = "form-control", placeholder = "Enter Your Password", type = "password" })
                    </div>
                    <span class="col-md-8 error">@ViewBag.messageLogin</span>
                </div>
            </div>
        </div>
 
    <div class="form-btn">
        <button type="submit" value="Submit" id="LoginButton" class="btn btn-outline-primary">Log in</button>
    </div>
    <div>
        <span class="have-account">@Html.ActionLink("Forgot Password", "ForgotPassword", "Login")</span>
    </div>
}